### PR TITLE
Add nixpkgs pin, bump haskell.nix

### PR DESCRIPTION
**Pull request by michaelpj**

### CODE REVIEW

**Comment by michaelpj** [comment]
Hydra is unhappy, but I built this locally and it's got most of the way, so I'm pretty confident.

**Comment by michaelpj** [comment]
And it builds.

**Comment by michaelpj** [comment]
@nc6 would you mind approving?

**Comment by michaelpj** [comment]
Oh dear, Haskell CI has been failing this way on master already...

**Review by nc6 — APPROVED** [review]
Approving for now to unblock, but we should aim to drop the separate nixpkgs pin and come back to using `nixpkgs` from `haskell.nix` before we update the base ref upstream.

**Pull request merged**
