### PR TITLE
Adding Keccak256 to cardano-crypto

### PR DESCRIPTION
**Pull request by iquerejeta**

### CODE REVIEW

**Comment by michaelpj** [comment]
Nag @dcoutts

**Comment by michaelpj** [comment]
Nag.

**Comment by nc6** [comment]
What's the use case for this, out of interest?

**Review by dcoutts — APPROVED** [review]

**Comment by iquerejeta** [comment]
> What's the use case for this, out of interest?
I think the motivation is that it is used in other ecosystems (read Ethereum).

**Comment by michaelpj** [comment]
:pray:

**Pull request merged**
