### PR TITLE
Fixes for building with nix

### PR DESCRIPTION
**Pull request by hamishmack**

### CODE REVIEW

**Comment by lehins** [comment]
@hamishmack Any luck with getting this problem fully fixed? It would be nice to unblock `master`, cause it currently doesn't build

**Comment by hamishmack** [comment]
This is working, but uses a branch of haskell.nix with updated HPC code.  That code looks like it breaks code coverage for ouroboros-network.

**Comment by lehins** [comment]
> That code looks like it breaks code coverage for ouroboros-network.

It's ok, ouroboros-network doesn't have to use the same index state or haskell.nix as cardano-base does.

**Comment by yvan-sraka** [comment]
I tested this and confirm it successfully fix `nix-shell` invocation :)

**Comment by hamishmack** [comment]
Then we could merge this, but keep in mind that we need to switch back the the haskell.nix/master branch once the hpc-patch is merged.

**Comment by lehins** [comment]
>  we need to switch back the the haskell.nix/master branch once the hpc-patch is merged.

I assume it will eventually get merged, then we'll update haskell.nix. Could you also link here the PR number of haskell.nix once one is created, so we don't forget about it and can see easier which PR we are waiting for.

**Comment by lehins** [comment]
> Then we could merge this

Yes!! Once you remove the WIP, I'll go ahead and merge it.

**Comment by hamishmack** [comment]
Haskell.nix PR is https://github.com/input-output-hk/haskell.nix/pull/1484

**Review by lehins — APPROVED** [review]

**Comment by lehins** [comment]
@hamishmack, thank you!

**Pull request merged**
