### PR TITLE
Drop cicero from flake

### PR DESCRIPTION
**Pull request by angerman**
Only hydra left now.

### CODE REVIEW

**Review by lehins — APPROVED** [review]
I am out of the loop on the CI plans, so does it mean we switching back to hydra from cicero in all of the repos?

Also, it looks like hydra CI is failing. My suspicion is it shouldn't be :slightly_smiling_face:

**Comment by jorisdral** [comment]
* Should https://github.com/input-output-hk/cardano-base/pull/418/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R13 also be removed?
* Some compilation errors could be solved by `nix flake lock --update-input CHaP`
* A benchmark build is failing in Hydra, and I think that's not showing up in the GitHub Actions CI because we don't build benchmarks there

**Comment by lehins** [comment]
Thanks @jorisdral 
Opened a ticket about benchmarks: https://github.com/input-output-hk/cardano-base/issues/427

**Comment by lehins** [comment]
Closing in favor of #428

**Pull request closed without merging**
