### PR TITLE
remove HashAlgorithm constraint from Show Hash

### PR DESCRIPTION
**Pull request by JaredCorduan**
And also add a `HeapWords` instance for `Hash`.

### CODE REVIEW

**Review by redxaxder — APPROVED** [review]

**Review by lehins — CHANGES_REQUESTED** [review]
This is a very dangerous thing to do! There is a much safer way.

**Comment by JaredCorduan** [comment]
> This is a very dangerous thing to do! There is a much safer way.

What do you suggest? I suspect you'll need to know what we are doing with the constructor?

**Comment by JaredCorduan** [comment]
@lehins the export is removed, instead I've added a `HeapWords` instance for `Hash` and we will deal with the other problem another way.

**Review by lehins — APPROVED** [review]
:+1:

**Pull request merged**
