### PR TITLE
strict-checked-vars: relaxed bounds io-sim-1.3.0.0

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by coot** [comment]
I will also add a revision in `CHaP`.

**Review by bolt12 — APPROVED** [review]

**Review by lehins — APPROVED** [review]
:+1:

**Comment by coot** [comment]
Oh, it got merged despite nix eval errors. Actually none of the checks are `required`, this doesn't look right.

**Comment by lehins** [comment]
>  this doesn't look right.

It is right. Hydra is unreliable in my opinion and it is impossible for a mere human to read those nix error messages. So, we do not block PRs just because nix fails.

That being said it would be nice if you could figure out how to fix it.

**Pull request merged**
