### PR TITLE
Ts haddock annotated

### PR DESCRIPTION
**Pull request by TimSheard**
Add additional Haddock documentation to Annotated.hs

There was a problem in building this repo using nix-shell, Serge Kosyrev made some fixes which involved using cabalWrapped in the nix shell file that allowed things to work.  This was  done in https://github.com/input-output-hk/cardano-base/pull/283
I have made this PR on top of that.  Someone who knows this repository should make sure that Serges fixes are approriate.

### CODE REVIEW

**Review by JaredCorduan — APPROVED** [review]
The haddocks themselves look great to me!

I don't know enough about the nix changes, though. (Or if there is another way to get the haddocks besides exposing the module).

**Comment by JaredCorduan** [comment]
This PR resolves https://github.com/input-output-hk/cardano-ledger/issues/2736

**Review by lehins — CHANGES_REQUESTED** [review]
Haddock looks good, although examples are totally broken. In an ideal world we'd have haddock examples that are executed by doctests that are run in CI (opened #285 so we can one day get to the ideal world). Few things we need to do before merging this PR:

1. Regardless of doctest, some examples is better then no examples, but we do need to make sure that examples we do add to the haddock at least initially are correct. So, I'd like to recommend validating any haddock example locally in the future before adding them to documentation. Because no examples is actually better then _broken_ examples. As far as examples in this PR are concerned, I ran them locally and when all suggestions are applied the should be ok.
2. Removing commits that adjust nix configuration, that fix is not the correct one for the problem you had experience. In fact the PR #283 that introduced them has been closed.
3. Remove all trailing white space in all files that have been touched by this PR. It can be achieved `M-x whitespace-cleanup` in emacs

**Review by lehins — APPROVED** [review]
:+1: Looks great.

**Pull request merged**
