### PR TITLE
Update index state to 2022-08-15T00:00:00Z

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Review by lehins — APPROVED** [review]

**Comment by L-as** [comment]
This broke master.

**Comment by lehins** [comment]
It sure did. sources need to be updated too.

**Comment by angerman** [comment]
Why didn't this break cardano-base's CI?

**Comment by lehins** [comment]
@angerman That is a very good question. Could it be due to the `cabal-wrapper`?

**Comment by hamishmack** [comment]
It looks like almost everything broke except the `required` job (the one that should aggregate everything we expect to work) https://hydra.iohk.io/eval/1267144

**Pull request merged**
