### PR TITLE
Also get FFI sizes via IO in error message

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Review by erikd — APPROVED** [review]

**Comment by newhoggy** [comment]
To investigate mysterious constant not-so-constant issue.

The issue being investigated is that `signKeySizeVRF` is supposed to return `64` always, but very rarely it returns something else like `58104768`. This change is to see if the C function is called again if it will subsequently give the correct result.

**Comment by newhoggy** [comment]
bors merge

**Comment by rvl** [comment]
Hi @newhoggy - [bors.toml](https://github.com/input-output-hk/cardano-base/blob/master/bors.toml) says that a Buildkite build is required. However there was no Buildkite build ever started for this branch. This repo does not have a `.buildkite/pipeline.yml`. You need to update `bors.toml` if you would like to merge with bors.

**Comment by newhoggy** [comment]
bors merge

**Comment by rvl** [comment]
@newhoggy It won't work - you need to either remove buildkite from `bors.toml` (for bors merge), or remove `bors.toml` altogether and merge with the button).

**Comment by newhoggy** [comment]
Oh, that PR is here: https://github.com/input-output-hk/cardano-base/pull/197

Hold on, I'm merge them together.

**Comment by newhoggy** [comment]
Thanks for the hint!

**Pull request merged**
