### PR TITLE
Add comment for `iterationCountKES` function

### PR DESCRIPTION
**Pull request by mgudemann**
`iterationCountKES` should return the number of times a KES signature key has already been updated

### CODE REVIEW

**Comment by mgudemann** [comment]
I'd be happy to rename this. Would `updateCountKES` be ok?

**Comment by edsko** [comment]
> I'd be happy to rename this. Would updateCountKES be ok?

I'd prefer that, but I think better still would be for `update` to take an argument (which period to move forward to); if that change is made, it's less that we are _counting how often_ we updated but rather "what is the current period" I guess..?

**Comment by mgudemann** [comment]
ok, fine with me. Then both passing a past period or a future period with too many evolutions would result in `Nothing`, right?

**Comment by edsko** [comment]
Just thinking out loud: perhaps a past period should result in an exception instead? In other words, `update` would take a precondition in terms of (the renamed vesion of) `udpateCount`? After all, doing so is a bug, whereas exceeding it's period is just something that can happen  and should be taken into account?

**Pull request merged**
